---
title: "Homework3"
author: "Yicong Zeng"
format: pdf
editor: visual
---

## Set up

```{r}
#| message: false
library(tidyverse)
library(readxl)
library(here)
library(janitor)
library(GGally)
library(MuMIn)
library(ggeffects)
library(gtsummary)
library(flextable)
library(modelsummary)
library(gt)
drought_exp <- read_xlsx(path = here("data", 
                                     "Valliere_etal_EcoApps_Data.xlsx"),
                         sheet = "First Harvest")
```

## Problem 1: Multiple linear regression: model selection and construction

a.  Make a table or list of all the models from class and the last one you constructed on your own. Write a caption for your table.

### Cleaning

```{r}
drought_exp_clean <- drought_exp %>% 
  clean_names() %>% # nicer column names
  mutate(species_name = case_when( # adding column with species scientific names
    species == "ENCCAL" ~ "Encelia californica", # bush sunflower
    species == "ESCCAL" ~ "Eschscholzia californica", # California poppy
    species == "PENCEN" ~ "Penstemon centranthifolius", # Scarlet bugler
    species == "GRICAM" ~ "Grindelia camporum", # great valley gumweed
    species == "SALLEU" ~ "Salvia leucophylla", # Purple sage
    species == "STIPUL" ~ "Nasella pulchra", # Purple needlegrass
    species == "LOTSCO" ~ "Acmispon glaber" # deerweed
  )) %>% 
  relocate(species_name, .after = species) %>% # moving species_name column after species
  mutate(water_treatment = case_when( # adding column with full treatment names
    water == "WW" ~ "Well watered",
    water == "DS" ~ "Drought stressed"
  )) %>% 
  relocate(water_treatment, .after = water) # moving water_treatment column after water
```

### Table
